chore: Migrate to null safety
Workiva/opentelemetry-dart pull request #100
Opened 2023-02-07 11:24 UTC by tatashidayat

## Which problem is this PR solving?
* This package is not useable on null-safety flutter.

Fixes #79

## Short description of the change
Just use Dart SDK >= 2.12 then run `dart migrate --skip-import-check`.

## How Has This Been Tested?
* Re-run the test
<img width="491" alt="image" src="https://user-images.githubusercontent.com/38237452/217232027-f68a51d5-33c2-4888-a6ea-b04a1626d91c.png">

## Checklist:
- [ ] Unit tests have been added
- [ ] Documentation has been updated

2023-02-07 11:26 UTC, aviary3-wk commented
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

2023-02-15 14:50 UTC, dustinlessard-wf approved these changes

2023-02-15 14:51 UTC, dustinlessard-wf requested changes
It looks like we have some work to do in fixing some issues the analyzer found.

2023-02-15 14:55 UTC, tatashidayat commented
> It looks like we have some work to do in fixing some issues the analyzer found.

Sure will do, looks like i used different sdk with ci

2023-02-15 17:12 UTC, blakeroberts-wk commented on Makefile
> +	dart pub global activate protoc_plugin 20.0.1
Perhaps it makes sense to do this upgrade in an independent PR to null safety

2023-02-15 17:32 UTC, tatashidayat commented
Hi @dustinlessard-wf, thanks for reviewing this PR.
I have updated my PR, please kindly review it again

2023-02-15 17:34 UTC, tatashidayat commented on Makefile
> +	dart pub global activate protoc_plugin 20.0.1
Sorry @blakeroberts-wk, I don't get it.
I updated to protoc_plugin to the null-safety version since the old one doesn't generate the null-safety code.

2023-02-15 17:54 UTC, blakeroberts-wk commented on Makefile
> +	dart pub global activate protoc_plugin 20.0.1
This is fair. However, is the only change between 19.3.1 and 20.0.1 null safety? Additionally, there's less discussion around what we should/shouldn't mark with a `?` in the generated code. But outside the generated code, it perhaps makes sense to enforce non-null values. For example, based on the [otel specifcation](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute), an attribute key must be non-null and non-empty string. So defining the attribute key as `String? key` is not to spec. It'd be nice to separate updating the generated code and updating the api/sdk (as much as possible, updating the generated code may require updates to the otlp exporter)

2023-02-16 04:05 UTC, tatashidayat commented on Makefile
> +	dart pub global activate protoc_plugin 20.0.1
If we want to have a null-safety proto class, then that would be enough.

Thanks for sharing the specs. I've updated my pr and made sure the attribute key should be non-null and not an empty string.

2023-02-16 10:52 UTC, EvgeniShmakov commented on lib/src/api/trace/span_id.dart
> +  bool get isValid => _id!.isEmpty || !_id!.every((i) => i == 0);
Hi @tatashidayat,

I think it should be isNotEmpty.
```suggestion
  bool get isValid => _id!.isNotEmpty || !_id!.every((i) => i == 0);
```

2023-02-16 16:05 UTC, EvgeniShmakov commented on lib/src/api/trace/span_id.dart
> +  bool get isValid => _id!.isEmpty || !_id!.every((i) => i == 0);
Actually, I tried to detect if it is a root span or not but it seems there is no good way.
I think I will create an extension to solve the issue then.

2023-02-16 18:07 UTC, blakeroberts-wk commented on lib/src/api/open_telemetry.dart
> +api.TextMapPropagator? get globalTextMapPropagator => _textMapPropagator;
The global text map propagator should never be null.

2023-02-16 18:07 UTC, blakeroberts-wk commented on lib/src/api/open_telemetry.dart
> +api.TextMapPropagator? _textMapPropagator;
This should not be null.

2023-02-16 18:08 UTC, blakeroberts-wk commented on lib/src/api/open_telemetry.dart
> +    {api.Context? context, api.Tracer? tracer}) async {
neither of these should be null

2023-02-16 18:08 UTC, blakeroberts-wk commented on lib/src/api/open_telemetry.dart
> +    {api.Context? context, api.Tracer? tracer}) {
neither of these should be null

2023-02-16 18:09 UTC, blakeroberts-wk commented on lib/src/api/span_processors/span_processor.dart
> +  void onStart(api.Span span, api.Context? parentContext);
Not sure if this should be null. I believe an empty context should be passed, never null.

2023-02-16 18:10 UTC, blakeroberts-wk commented on lib/src/api/trace/nonrecording_span.dart
> +  set name(String? _name) {}
a span name should not be null

2023-02-16 18:10 UTC, blakeroberts-wk commented on lib/src/api/trace/nonrecording_span.dart
> +  void setStatus(api.StatusCode status, {String? description}) {}
a description should not be null

2023-02-16 18:11 UTC, blakeroberts-wk commented on lib/src/api/trace/nonrecording_span.dart
> +      {List<api.Attribute>? attributes}) {}
if attributes are supplied, the list should not be null

2023-02-16 18:13 UTC, blakeroberts-wk commented on lib/src/api/trace/noop_tracer.dart
> +    final parentContext = context!.spanContext!;
the default value would be `sdk.SpanContext.invalid()`

2023-02-16 18:14 UTC, blakeroberts-wk commented on lib/src/api/trace/span.dart
> +  api.SpanContext? get spanContext;
For any field on a span, we should enforce returning non-null values

2023-02-16 18:20 UTC, blakeroberts-wk commented on lib/src/api/open_telemetry.dart
> +    {api.Context? context, api.Tracer? tracer}) async {
I may have misspoke on asking for the removal of `?` on optional parameters. Perhaps the type _must_ be nullable because it is an optional parameter? In which case, any optional parameter should always have a `?` and in the majority of cases we'll need to ensure all optional parameters are assigned to if null (such as below this line with `context ??= api.Context.current`)

2023-02-16 18:21 UTC, blakeroberts-wk commented on lib/src/api/open_telemetry.dart
> +    {api.Context? context, api.Tracer? tracer}) {
nvm

2023-02-16 18:22 UTC, blakeroberts-wk commented on lib/src/api/span_processors/span_processor.dart
> +  void onStart(api.Span span, api.Context? parentContext);
So I believe the argument here should be one of: manually passed context, current context, or invalid context. Null should not be a valid value

2023-02-16 18:22 UTC, blakeroberts-wk commented on lib/src/api/trace/nonrecording_span.dart
> +  void setStatus(api.StatusCode status, {String? description}) {}
nvm

2023-02-16 18:23 UTC, blakeroberts-wk commented on lib/src/api/trace/nonrecording_span.dart
> +      {List<api.Attribute>? attributes}) {}
nvm

2023-02-16 18:24 UTC, blakeroberts-wk commented on lib/src/api/trace/span_link.dart
> +  final api.SpanContext? _context;
this should not be null

2023-02-16 18:36 UTC, blakeroberts-wk commented on lib/src/sdk/metrics/meter_provider.dart
> +  api.Meter? get(String? name,
a null meter should never be returned and a null name should never be given

2023-02-16 18:37 UTC, blakeroberts-wk commented on lib/src/sdk/metrics/state/meter_shared_state.dart
> +  sdk.Meter? meter;
this should not be null

2023-02-16 18:41 UTC, blakeroberts-wk commented on lib/src/sdk/trace/exporters/collector_exporter.dart
> +  late http.Client client;
I don't believe `late` is accurate. But this client should be final (as well as the uri)

2023-02-16 18:42 UTC, blakeroberts-wk commented on lib/src/sdk/trace/exporters/collector_exporter.dart
> +        <sdk.Resource?, Map<api.InstrumentationLibrary, List<pb_trace.Span>>>{};
null values should not be used as map keys

2023-02-16 18:44 UTC, blakeroberts-wk commented on lib/src/sdk/trace/exporters/collector_exporter.dart
> +    late pb_trace.Status_StatusCode statusCode;
why would this be marked as late and not `spanKind`? I'm not sure `late` is necessary here

2023-02-16 18:45 UTC, blakeroberts-wk commented on lib/src/sdk/trace/exporters/collector_exporter.dart
> +  pb_common.AnyValue _attributeValueToProtobuf(Object? value) {
the value should never be null

2023-02-16 18:46 UTC, blakeroberts-wk commented on lib/src/sdk/trace/exporters/collector_exporter.dart
> +        endTimeUnixNano: span.endTime!,
we should ensure none of these are ever null by updating the span interface appropriately

2023-02-16 18:47 UTC, blakeroberts-wk commented on lib/src/sdk/trace/exporters/console_exporter.dart
> +        'state': '${span.spanContext!.traceState}',
null should not be allowed in any of these values

2023-02-16 18:50 UTC, blakeroberts-wk commented on lib/src/sdk/trace/sampling/always_off_sampler.dart
>          context.spanContext?.traceState ?? sdk.TraceState.empty());
we should have `context.spanContext` never be null as well as `context.spanContext.traceState`

2023-02-16 18:51 UTC, blakeroberts-wk commented on lib/src/sdk/trace/sampling/always_off_sampler.dart
>          context.spanContext?.traceState ?? sdk.TraceState.empty());
this applies to https://github.com/Workiva/opentelemetry-dart/pull/100/files#diff-f839cde4d5973aba18110801159356342c4d082fc7040989030b7847b028eaf1R20 as well

2023-02-16 18:51 UTC, blakeroberts-wk commented on lib/src/sdk/trace/sampling/parent_based_sampler.dart
>      if (parentSpanContext == null || !parentSpanContext.isValid) {
```suggestion
    final parentSpanContext = context.spanContext;

    if (!parentSpanContext.isValid) {
```

2023-02-16 18:52 UTC, blakeroberts-wk commented on lib/src/sdk/trace/sampling/sampling_result.dart
> +  final List<api.Attribute>? spanAttributes;
I think it makes sense to make this an empty list and not null

2023-02-16 18:53 UTC, blakeroberts-wk commented on lib/src/sdk/trace/span.dart
>  class Span implements api.Span {
we're going to want things to be null as little as possible. I'm guessing the majority of the `?` in this file should be removed

2023-02-16 18:56 UTC, blakeroberts-wk commented on lib/src/sdk/trace/span.dart
> +      List<api.SpanLink>? links, sdk.SpanLimits limits) {
```suggestion
      List<api.SpanLink> links, sdk.SpanLimits limits) {
```

2023-02-16 18:57 UTC, blakeroberts-wk commented on lib/src/sdk/trace/span.dart
> +      final attributeMap = <String?, int>{};
```suggestion
      final attributeMap = <String, int>{};
```

2023-02-16 18:57 UTC, blakeroberts-wk commented on lib/src/sdk/trace/span.dart
> +      if (!link.context!.isValid) continue;
```suggestion
      if (!link.context.isValid) continue;
```

2023-02-16 19:00 UTC, blakeroberts-wk commented on lib/src/sdk/trace/span_limits.dart
> +  late int _maxNumAttributeLength;
I'm not sure `late` is accurate here

2023-02-16 19:00 UTC, blakeroberts-wk commented on lib/src/sdk/trace/span_processors/batch_processor.dart
> +  Timer? _timer;
```suggestion
  Timer _timer;
```

2023-02-16 19:01 UTC, blakeroberts-wk commented on lib/src/sdk/trace/span_processors/batch_processor.dart
> +    _timer!.cancel();
```suggestion
    _timer.cancel();
```

2023-02-16 19:06 UTC, blakeroberts-wk commented on lib/src/sdk/trace/tracer.dart
> +      traceState = parent.spanContext!.traceState;
```suggestion
      parentSpanId = parent.spanContext.spanId;
      traceId = parent.spanContext.traceId;
      traceState = parent.spanContext.traceState;
```

2023-02-16 19:11 UTC, blakeroberts-wk commented on test/integration/open_telemetry_test.dart
> +    Span? span;
I feel like this would be a time where `late` is appropriate and `?` can be removed?

2023-02-17 02:43 UTC, tatashidayat commented on lib/src/api/open_telemetry.dart
> +api.TextMapPropagator? get globalTextMapPropagator => _textMapPropagator;
I don't think so @blakeroberts-wk, if the user doesn't invoke `registerGlobalTextMapPropagator` then it will be null.

2023-02-17 02:51 UTC, tatashidayat commented on lib/src/api/open_telemetry.dart
> +api.TextMapPropagator? _textMapPropagator;
I don't think so @blakeroberts-wk, if the user doesn't invoke registerGlobalTextMapPropagator then it will be null.

2023-02-17 02:54 UTC, tatashidayat commented on lib/src/api/open_telemetry.dart
> +    {api.Context? context, api.Tracer? tracer}) async {
I think those are optional @blakeroberts-wk

2023-02-17 02:54 UTC, tatashidayat commented on lib/src/api/open_telemetry.dart
> +    {api.Context? context, api.Tracer? tracer}) {
I think those are optional @blakeroberts-wk

2023-02-17 06:27 UTC, tatashidayat commented on lib/src/api/span_processors/span_processor.dart
> +  void onStart(api.Span span, api.Context? parentContext);
I don't think so @baileyjensen-wk.
since the Span constructor, the parentContext is nullable and the _processor is invoked with the nullable parentContext.
```dart
/// Construct a [Span].
  Span(this.name, this._spanContext, this._parentSpanId, this._processors,
      this._timeProvider, this._resource, this._instrumentationLibrary,
      {api.SpanKind? kind,
      List<api.Attribute>? attributes,
      List<api.SpanLink>? links,
      api.Context? parentContext,
      sdk.SpanLimits? limits,
      Int64? startTime})
      : _links = _applyLinkLimits(links, limits ?? sdk.SpanLimits()),
        _kind = kind ?? api.SpanKind.internal,
        _startTime = startTime ?? _timeProvider.now,
        _limits = limits ?? sdk.SpanLimits() {
    if (attributes != null) {
      setAttributes(attributes);
    }

    for (var i = 0; i < _processors.length; i++) {
      _processors[i].onStart(this, parentContext);
    }
  }
  ```

2023-02-17 06:32 UTC, tatashidayat commented on lib/src/api/trace/nonrecording_span.dart
> +      {List<api.Attribute>? attributes}) {}
I'm afraid we can't have a non-null optional param unless we have the default value

2023-02-17 06:41 UTC, tatashidayat commented on lib/src/api/trace/nonrecording_span.dart
> +  void setStatus(api.StatusCode status, {String? description}) {}
I'll make empty as the default value.

2023-02-17 06:41 UTC, tatashidayat commented on lib/src/api/trace/nonrecording_span.dart
> +      {List<api.Attribute>? attributes}) {}
If you want to enforce it, then i can set empty list as the default value.

2023-02-17 06:50 UTC, tatashidayat commented on lib/src/api/trace/noop_tracer.dart
> +    final parentContext = context!.spanContext!;
Context.spanContext is nullable
```dart
  /// Get the [api.SpanContext] from this [Context], or null if no such
  /// [api.SpanContext] exists.
  api.SpanContext? get spanContext => getValue(spanKey)?.spanContext;
```
if you're concerned with `context`, I'll make it something like this, to make sure we always have a spanContext:
```dart
    final parentContext = (context ?? api.Context.current).spanContext ??
        sdk.SpanContext.invalid();

    return api.NonRecordingSpan(parentContext);
```

2023-02-17 06:54 UTC, tatashidayat commented on lib/src/api/trace/span.dart
> +  api.SpanContext? get spanContext;
Sure, will make it non-nullable

2023-02-17 07:05 UTC, tatashidayat commented on lib/src/sdk/trace/exporters/collector_exporter.dart
> +  late http.Client client;
Since we provide an optional client on the constructor and we can't set http.Client() isn't a const constructor, so we need to make it a late variable. And I agree, we should make it final.

2023-02-17 07:12 UTC, tatashidayat commented on lib/src/sdk/trace/exporters/collector_exporter.dart
> +    late pb_trace.Status_StatusCode statusCode;
Yeah, I think we can remove late keyword

2023-02-17 07:13 UTC, tatashidayat commented on lib/src/sdk/trace/exporters/collector_exporter.dart
> +  pb_common.AnyValue _attributeValueToProtobuf(Object? value) {
sure, i'll make it non-nullable

2023-02-17 07:24 UTC, tatashidayat commented on lib/src/sdk/trace/span_processors/batch_processor.dart
> +  Timer? _timer;
I think we should leave timer to be null since it will only exist if `_startTimer` has been invoked

2023-02-17 07:37 UTC, tatashidayat commented
Hi @blakeroberts-wk,
I have updated my PR and made some adjustments. I can't force all to be non-nullable. If the comments/docs say it might be null, then I leave it to be nullable.

Please kindly review it again

2023-02-17 17:12 UTC, blakeroberts-wk commented on lib/src/api/open_telemetry.dart
> +api.TextMapPropagator? get globalTextMapPropagator => _textMapPropagator;
That should not be the case. If a user does not register a global text map, a no-op should be returned (potentially a w3c propagator might need to be registered by default, but I assume it should be a no-op. we'll need to consult the spec)

2023-02-17 17:17 UTC, blakeroberts-wk commented on lib/src/api/span_processors/span_processor.dart
> +  void onStart(api.Span span, api.Context? parentContext);
Instead of allowing a null-able parent context, it should be that an invalid context is passed as the parent. The constructor of the span should be used internally only. The constructor should be invoked by the tracer's start span method. This method should set the parent context to context.current by default (which should never be null), or to a context supplied by the user (which should never be null even though its type is null-able because it is an optional parameter).

2023-02-18 11:54 UTC, tatashidayat commented on lib/src/api/span_processors/span_processor.dart
> +  void onStart(api.Span span, api.Context? parentContext);
Alright, if parent context null, then i'll use current one.
So it become like this:
```dart
/// Construct a [Span].
  Span(this.name, this._spanContext, this._parentSpanId, this._processors,
      this._timeProvider, this._resource, this._instrumentationLibrary,
      {api.SpanKind? kind,
      List<api.Attribute>? attributes,
      List<api.SpanLink>? links,
      api.Context? parentContext,
      sdk.SpanLimits? limits,
      Int64? startTime})
      : _links = _applyLinkLimits(links ?? [], limits ?? sdk.SpanLimits()),
        _kind = kind ?? api.SpanKind.internal,
        _startTime = startTime ?? _timeProvider.now,
        _limits = limits ?? sdk.SpanLimits() {
    final pContext = parentContext ?? Context.current;

    if (attributes != null) {
      setAttributes(attributes);
    }

    for (var i = 0; i < _processors.length; i++) {
      _processors[i].onStart(this, pContext);
    }
  }
```

2023-02-21 07:08 UTC, tatashidayat commented on lib/src/sdk/trace/exporters/collector_exporter.dart
> +        <sdk.Resource?, Map<api.InstrumentationLibrary, List<pb_trace.Span>>>{};
Sure @blakeroberts-wk, I have update it, please review it again

2023-02-22 08:54 UTC, tatashidayat commented
Hi @blakeroberts-wk, could you help to review it again?
I've made the map key to be non-nullable.

2023-02-26 02:02 UTC, tatashidayat commented
Hi @blakeroberts-wk, could you help to review it again?
I think i have address all of your comments

2023-03-03 02:57 UTC, tatashidayat commented
Hi @blakeroberts-wk @dustinlessard-wf, The CI failed on `Run romeovs/lcov-reporter-action@v0.2.16` due to
 ```
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/romeovs/lcov-reporter-action/v0.2.16/dist/main.js:6018:23
    at processTicksAndRejections (internal/process/task_queues.js:[9](https://github.com/Workiva/opentelemetry-dart/actions/runs/4229279572/jobs/7532067808#step:13:10)7:5)
    at async main$1 (/home/runner/work/_actions/romeovs/lcov-reporter-action/v0.2.16/dist/main.js:229[11](https://github.com/Workiva/opentelemetry-dart/actions/runs/4229279572/jobs/7532067808#step:13:12):2) {
  status: 403,RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/romeovs/lcov-reporter-action/v0.2.16/dist/main.js:6018:23
    at processTicksAndRejections (internal/process/task_queues.js:[9](https://github.com/Workiva/opentelemetry-dart/actions/runs/4229279572/jobs/7532067808#step:13:10)7:5)
    at async main$1 (/home/runner/work/_actions/romeovs/lcov-reporter-action/v0.2.16/dist/main.js:229[11](https://github.com/Workiva/opentelemetry-dart/actions/runs/4229279572/jobs/7532067808#step:13:12):2) {
  status: 403,
 ```

I'm not sure what to do to fix it. Perhaps the GitHub token expired.

2023-03-13 02:37 UTC, tatashidayat commented
Hi @dustinlessard-wf, any update for this PR?

2023-03-29 07:36 UTC, Pascal-Orthopy commented
Hello @dustinlessard-wf, are there any updates? We are already waiting for this PR to be merged as null-safety will be enforced with [Dart 3*] (https://dart.dev/null-safety#dart-3-and-null-safety). Also, we are only allowed to use null-safety packages. We know that it is always difficult to run open-source packages and manage PRs from external parties, so we just want to know if this PR will be merged in the near future.

2023-04-18 19:48 UTC, dustinlessard-wf approved these changes

2023-05-20 11:15 UTC, dustinlessard-wf commented
Circling back on this... apologies @tatashidayat for the less-than-timely communication.  I intended to update you shortly after your last comment but failed miserably.

Some internal discussions resulted in this pr being held up because the engineers responsible for this code would like to see a more intentional approach to migrate it to null safety.  We have an internal project in progress to ensure all of our Dart libraries are null-safe, though we haven't specifically scheduled this one yet.  

@blakeroberts-wk @tylerrinnan-wf , could you comment on the timing that can be expected for this codebase to be null-safe and what we intend to do with this pull request?

FYI @robbecker-wf

2023-08-24 16:32 UTC, blakeroberts-wk commented
Update regarding project status and null-safety:

Recently, we have struggled to prioritize opentelemetry-dart related tasks. We are working to shore up this shortcoming which will include migration to null-safety.

However, we have identified some discrepancies between the OpenTelemetry specification and this library's implementation. We believe prioritizing null-safety before alignment to the OpenTelemetry specification on a portion of the aforementioned discrepancies may result in unnecessary API thrashing.

We expect breaking changes to the API as we work to align this project to the OpenTelemetry specification and migrate the project to null-safety. We will attempt to minimize the number and impact of these changes as much as possible.

As for a timeline on null-safety, we aim to begin addressing discrepancies with the OpenTelemetry specification in about two weeks. We expect to finish this effort and begin working on migration to null-safety by the end of Q3. We expect to have migrated this project to null-safety by early Q4.

2023-11-10 19:05 UTC, robbecker-wf commented
Closing. Null safety was completed in https://github.com/Workiva/opentelemetry-dart/pull/129

2023-11-10 19:05 UTC, closed without merging