Extender exporter with credential for authorization
Workiva/opentelemetry-dart pull request #102
Opened 2023-03-08 10:14 UTC by v-shemet

`CollectorExporter` has been extended with credentials (`apiKey` or `secretToken`) in order to be able to authorize requests to APM Server.

2023-03-08 10:16 UTC, aviary-wf commented
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

2023-03-08 15:31 UTC, blakeroberts-wk commented on lib/src/sdk/trace/exporters/collector_exporter.dart
> +  CollectorExporter(this.uri, {http.Client httpClient, this.credential}) {
Rather than accepting credentials directly, perhaps we should allow supplying a headers map

2023-03-09 16:14 UTC, blakeroberts-wk approved these changes

2023-05-05 19:29 UTC, kennytrytek-wf requested changes
Hello, I'm sorry for the long hiatus between reviews. I believe the only thing holding this PR up from being merged is a QA review. This can be done manually, though a unit test would be a better addition.

The default case when headers are not supplied has been shown to behave the same way as before, but not the case when headers are given. Please add a unit test to show that supplied headers are correctly propagated to the `post` call.

2023-05-17 17:55 UTC, v-shemet commented
> Hello, I'm sorry for the long hiatus between reviews. I believe the only thing holding this PR up from being merged is a QA review. This can be done manually, though a unit test would be a better addition.
> 
> The default case when headers are not supplied has been shown to behave the same way as before, but not the case when headers are given. Please add a unit test to show that supplied headers are correctly propagated to the `post` call.

Hi @kennytrytek-wf , thanks for the feedback. I covered the logic with unit tests in the commit: d4c2c6a8cbb2722f06912cc7d6b022cc9ed07e14

2023-05-17 18:05 UTC, blakeroberts-wk approved these changes

2023-05-17 19:40 UTC, kennytrytek-wf commented
The unit test is sufficient to show that this is functional.
QA +1 ⛄ 

@Workiva/release-management-pp

2023-05-20 10:59 UTC, dustinlessard-wf approved these changes

2023-05-20 10:59 UTC, dustinlessard-wf commented
QA +1
@Workiva/release-management-p

2023-05-20 11:06 UTC, merged