Otel logs
Workiva/opentelemetry-dart pull request #169
Opened 2024-05-20 08:17 UTC by provRushabhShah

## Which problem is this PR solving?

Added Logs in this framework
Added LogExpoter, Provider, Logger object,  protobuffer 

## Checklist:

- [ ] Unit tests have been added

2024-05-20 08:18 UTC, aviary2-wf commented
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

2024-05-20 15:22 UTC, changliu-wk commented
@provRushabhShah  please run `make analyze`.

2024-09-16 12:14 UTC, yorkvolvo commented
can we move forward this log feature?

2024-09-16 16:17 UTC, blakeroberts-wk requested changes
I believe these changes are a work in progress.

We'll want to clean this up and break out the implementation. For starters, we'll want to:
- remove dev env specific files
- ensure added files have the copy write notice at the top and a trailing new line at the end
- folder and file names should be lower case
- break up the changes into multiple PRs for easier review. The first PR I would suggest is the one adding the generated protobuf code

2025-01-06 03:48 UTC, yuzurihaaa commented
Hi. Can I know if this PR is still ongoing? If not, I would like to start creating PRs for this feature.

Currently in my job, I am looking to replace our custom remote log to opentelemetry standard and expected to use it by Q1 this year so I have time to actively work on this.

At this point, the code in my repo already worked with OpenTelemetryCollector and Loki as well as visualising Grafana.

I am not an expert in this field, so would appreciate for some 👀 and guidance too :) 

Also thanks to this PR as it helped me a lot on some parts.

2025-01-10 03:50 UTC, yuzurihaaa commented
I've create [PRs](https://github.com/Workiva/opentelemetry-dart/pulls/yuzurihaaa). If this PR continues, then I'll close mine.

2026-05-15 09:58 UTC, dustinlessard-wf commented
Hi @provRushabhShah  
Thank you for taking the time to contribute to this project. We really appreciate the effort you put into opening this pull request.
I want to be transparent about the state of the repository: we have not been actively maintaining this codebase, and we do not currently have the bandwidth to properly review, test, and support external contributions at the standard they deserve.
For that reason, we’re going to close this pull request. This is not a reflection on the quality or value of your contribution. Rather, it reflects our current inability to responsibly vet and merge changes into the project.
We are also exploring a path to transfer ownership or stewardship of the project outside of our company, so that it can hopefully have a more active and sustainable future. Until that direction is clearer, we do not want to create a misleading impression that the repository is actively maintained or that we can support merged changes going forward.
Thank you again for your contribution and for your interest in improving the project. We’re sorry we were not able to engage with your pull request in the way it deserved.

2026-05-15 09:58 UTC, closed without merging